name: Analyze chat trend

on:
    workflow_dispatch:
        inputs:
            url:
                description: "Input URL for the Live to Analyze"
                required: true
                default: "https://example.com"
            tracking_id:
                description: "Unique tracking ID for this run"
                required: true
                default: ""

jobs:
  Analyze-Chat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env

    - name: Ensure directory exists
      run: |
        mkdir -p csv_files charts

    - name: Run script
      run: |
        python main.py "${{github.event.inputs.url}}"

    - name: Upload generated files
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: generated-images-${{ github.event.inputs.tracking_id }}
        path: charts/
